// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlmXDkma3C0b5Qxz3rrCtIKQK00YdtVJ4',
    appId: '1:421317490668:web:bf994e1e3cf094ca5fb2c9',
    messagingSenderId: '421317490668',
    projectId: 'questy-c8fa9',
    authDomain: 'questy-c8fa9.firebaseapp.com',
    storageBucket: 'questy-c8fa9.firebasestorage.app',
    measurementId: 'G-ZZXD18MF6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdVBqVKcVdly9XR2QgA09MmFKblZp7Pw',
    appId: '1:421317490668:android:ab195c2dc25f5a9e5fb2c9',
    messagingSenderId: '421317490668',
    projectId: 'questy-c8fa9',
    storageBucket: 'questy-c8fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7y0Ds5Ugw3LSXwVSir78CbV3QTXeQxgM',
    appId: '1:421317490668:ios:b5e6f9a7ce95149b5fb2c9',
    messagingSenderId: '421317490668',
    projectId: 'questy-c8fa9',
    storageBucket: 'questy-c8fa9.firebasestorage.app',
    iosBundleId: 'com.example.questy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7y0Ds5Ugw3LSXwVSir78CbV3QTXeQxgM',
    appId: '1:421317490668:ios:b5e6f9a7ce95149b5fb2c9',
    messagingSenderId: '421317490668',
    projectId: 'questy-c8fa9',
    storageBucket: 'questy-c8fa9.firebasestorage.app',
    iosBundleId: 'com.example.questy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlmXDkma3C0b5Qxz3rrCtIKQK00YdtVJ4',
    appId: '1:421317490668:web:3902151e3365ba085fb2c9',
    messagingSenderId: '421317490668',
    projectId: 'questy-c8fa9',
    authDomain: 'questy-c8fa9.firebaseapp.com',
    storageBucket: 'questy-c8fa9.firebasestorage.app',
    measurementId: 'G-31TE3BS2TR',
  );
}
